# CircleCI Firebase Deployment Config
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/ate-o-futuro/vue-app
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "./vue-app/package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Go to proper folder
          command: cd /
      - save_cache:
          key: v1-npm-deps-{{ checksum "./vue-app/package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Vue Build
          command: npm run --prefix ../../../ate-o-futuro/vue-app build
      - run:
          name: Firebase Deploy
          command: ../../../ate-o-futuro/vue-app/node_modules/.bin/firebase deploy --only hosting --token "$FIREBASE_TOKEN"